env:
  browser: true
  es2021: true
  node: true

extends:
  - eslint:recommended
  - '@typescript-eslint/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:react/jsx-runtime'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 'latest'
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - '@typescript-eslint'
  - 'react'
  - 'react-hooks'
  - 'react-refresh'

settings:
  react:
    version: 'detect'

rules:
  '@typescript-eslint/no-unused-vars': 'warn'
  '@typescript-eslint/no-explicit-any': 'warn'
  'no-console': 'warn'
  'prefer-const': 'error'
  'react-refresh/only-export-components': ['warn', { 'allowConstantExport': true }]

overrides:
  # Disable react-refresh for Next.js public website (legitimate metadata exports)
  - files: ['public-website/**/*.{ts,tsx}']
    rules:
      'react-refresh/only-export-components': 'off'
  
  # Allow non-prod files to export helpers next to components
  - files: ['**/*.stories.*', '**/*.test.*', '**/__examples__/**']
    rules:
      'react-refresh/only-export-components': 'off'
  
  # Soften app UI temporarily for gradual improvement
  - files: ['src/**/*.{ts,tsx}']
    rules:
      '@typescript-eslint/no-explicit-any': 'warn'
      '@typescript-eslint/no-require-imports': 'warn'
      'react-hooks/exhaustive-deps': 'warn'
  
  # Keep autonomous agents strict
  - files: ['src/agents/**/*.{ts,tsx}', 'autonomous-system/**/*.{ts,tsx}']
    rules:
      '@typescript-eslint/no-explicit-any': 'error'
      '@typescript-eslint/no-require-imports': 'error'
      'react-hooks/exhaustive-deps': 'off'
