version: '3.8'

services:
  tms-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: tms-logistics-lynx
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      # Mount environment file for configuration
      - ./.env:/app/.env:ro
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Mount artifacts directory for autonomous system outputs
      - ./artifacts:/app/artifacts
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "dist/monitoring/health-check.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - tms-network

  # Development service (optional)
  tms-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: tms-logistics-lynx-dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src
      - ./public:/app/public
      - ./.env:/app/.env:ro
      - ./logs:/app/logs
      - ./artifacts:/app/artifacts
    command: ["npm", "run", "dev"]
    profiles:
      - dev
    networks:
      - tms-network

networks:
  tms-network:
    driver: bridge

volumes:
  tms-logs:
  tms-artifacts:
