# GitHub Actions workflow for Autonomous TMS Deployment
# This workflow handles testing, deployment, and monitoring of the autonomous TMS system
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# Note: Secret context access warnings (${{ secrets.* }}) are false positives - this syntax is correct for GitHub Actions
# The warnings about "Context access might be invalid" are false positives from the YAML language server
# GitHub Actions properly supports ${{ secrets.SECRET_NAME }} syntax in env sections
# All ${{ secrets.* }} references in this file are valid GitHub Actions syntax
# The YAML language server incorrectly flags these as invalid context access
# 
# IMPORTANT: The "Context access might be invalid" warnings are FALSE POSITIVES
# These warnings can be safely ignored as they are valid GitHub Actions syntax
# The workflow will execute correctly despite these warnings
name: Autonomous TMS Deployment

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Manual trigger

env:
  NODE_VERSION: '18'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint
        
      - name: Run tests
        run: npm test
        
      - name: Build application
        run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate required secrets
        run: |
          # Check if required secrets are set
          if [ -z "$SUPABASE_URL" ]; then
            echo "Error: SUPABASE_URL secret is not set"
            exit 1
          fi
          if [ -z "$SUPABASE_ANON_KEY" ]; then
            echo "Error: SUPABASE_ANON_KEY secret is not set"
            exit 1
          fi
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "Error: OPENAI_API_KEY secret is not set"
            exit 1
          fi
          
          # Check n8n secrets (optional but both must be set together)
          if [ -n "$N8N_BASE_URL" ] && [ -z "$N8N_API_KEY" ]; then
            echo "Error: N8N_BASE_URL is set but N8N_API_KEY is missing"
            exit 1
          fi
          if [ -z "$N8N_BASE_URL" ] && [ -n "$N8N_API_KEY" ]; then
            echo "Error: N8N_API_KEY is set but N8N_BASE_URL is missing"
            exit 1
          fi
          
          if [ -n "$N8N_BASE_URL" ] && [ -n "$N8N_API_KEY" ]; then
            echo "N8N integration is enabled"
            echo "N8N_ENABLED=true" >> $GITHUB_ENV
          else
            echo "N8N integration is disabled - both N8N_BASE_URL and N8N_API_KEY must be set"
            echo "N8N_ENABLED=false" >> $GITHUB_ENV
          fi
          
          echo "All required secrets are configured"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          N8N_BASE_URL: ${{ secrets.N8N_BASE_URL }}
          N8N_API_KEY: ${{ secrets.N8N_API_KEY }}
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Setup database
        run: npm run db:setup
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          
      - name: Deploy n8n workflows
        if: env.N8N_ENABLED == 'true'
        run: npm run n8n:deploy
        env:
          N8N_BASE_URL: ${{ secrets.N8N_BASE_URL || '' }}
          N8N_API_KEY: ${{ secrets.N8N_API_KEY || '' }}
          
      - name: Deploy to production
        run: npm run deploy:prod
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
      - name: Health check
        run: npm run health:check
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          
      - name: Test workflows
        if: env.N8N_ENABLED == 'true'
        run: npm run test:workflows
        env:
          N8N_BASE_URL: ${{ secrets.N8N_BASE_URL || '' }}
          N8N_API_KEY: ${{ secrets.N8N_API_KEY || '' }}
          
      - name: Test agents
        run: npm run test:agents
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          
      - name: Start autonomous system
        run: npm run start:autonomous &
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          N8N_BASE_URL: ${{ secrets.N8N_BASE_URL || '' }}
          N8N_API_KEY: ${{ secrets.N8N_API_KEY || '' }}
          
      - name: Wait for system startup
        run: sleep 30
        
      - name: Verify deployment
        run: |
          # Check if autonomous system is running
          curl -f http://localhost:3000/api/health || exit 1
          
          # Check if n8n workflows are active (only if N8N is enabled)
          if [ "$N8N_ENABLED" = "true" ]; then
            curl -f "$N8N_BASE_URL/api/v1/workflows" \
              -H "Authorization: Bearer $N8N_API_KEY" || exit 1
          else
            echo "N8N integration is disabled, skipping workflow verification"
          fi
        env:
          N8N_BASE_URL: ${{ secrets.N8N_BASE_URL || '' }}
          N8N_API_KEY: ${{ secrets.N8N_API_KEY || '' }}
          N8N_ENABLED: ${{ env.N8N_ENABLED }}
          
      - name: Notify success
        if: success()
        run: |
          curl -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '{
              "status": "deployed",
              "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'",
              "environment": "production",
              "commit": "'${{ github.sha }}'",
              "branch": "'${{ github.ref }}'"
            }'
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOYMENT_WEBHOOK_URL || '' }}
          
      - name: Notify failure
        if: failure()
        run: |
          curl -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d '{
              "status": "failed",
              "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'",
              "environment": "production",
              "commit": "'${{ github.sha }}'",
              "branch": "'${{ github.ref }}'",
              "error": "Deployment failed"
            }'
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOYMENT_WEBHOOK_URL || '' }}

  monitor:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Start monitoring
        run: npm run monitor:start
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          N8N_BASE_URL: ${{ secrets.N8N_BASE_URL || '' }}
          N8N_API_KEY: ${{ secrets.N8N_API_KEY || '' }}
          
      - name: Monitor for 5 minutes
        run: sleep 300
        
      - name: Check system health
        run: npm run health:check
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          
      - name: Report monitoring results
        run: |
          echo "Monitoring completed successfully"
          echo "System is running autonomously"
        if: success()
