# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 🏠 Local Validation (No Network)

on:
  workflow_dispatch:
  push:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  local-validation:
    name: 🏠 Local Code Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      
      - name: 🔍 Validate Repository Structure
        run: |
          echo "🔍 Validating repository structure..."
          
          # Check key directories
          if [ -d "logistics-lynx" ]; then
            echo "✅ logistics-lynx directory found"
          else
            echo "❌ logistics-lynx directory missing"
            exit 1
          fi
          
          if [ -d ".github/workflows" ]; then
            echo "✅ .github/workflows directory found"
          else
            echo "❌ .github/workflows directory missing"
            exit 1
          fi
          
          # Check key files
          if [ -f "logistics-lynx/package.json" ]; then
            echo "✅ package.json found"
          else
            echo "❌ package.json missing"
            exit 1
          fi
          
          echo "✅ Repository structure validation passed"
      
      - name: 🔍 Validate YAML Syntax
        run: |
          echo "🔍 Validating YAML syntax..."
          
          # Check workflow files
          for workflow in .github/workflows/*.yml; do
            if [ -f "$workflow" ]; then
              echo "📋 Checking $workflow..."
              # Basic YAML validation
              if head -1 "$workflow" | grep -q "^\s*#\|^\s*name:\|^\s*on:"; then
                echo "✅ $workflow appears valid"
              else
                echo "⚠️ $workflow may have syntax issues"
              fi
            fi
          done
          
          echo "✅ YAML validation completed"
      
      - name: 🔍 Validate JSON Files
        run: |
          echo "🔍 Validating JSON files..."
          
          # Check package.json
          if [ -f "logistics-lynx/package.json" ]; then
            if python3 -m json.tool logistics-lynx/package.json > /dev/null 2>&1; then
              echo "✅ package.json is valid JSON"
            else
              echo "❌ package.json has JSON syntax errors"
              exit 1
            fi
          fi
          
          # Check other JSON files
          for json_file in *.json; do
            if [ -f "$json_file" ]; then
              echo "📋 Checking $json_file..."
              if python3 -m json.tool "$json_file" > /dev/null 2>&1; then
                echo "✅ $json_file is valid JSON"
              else
                echo "⚠️ $json_file may have JSON syntax issues"
              fi
            fi
          done
          
          echo "✅ JSON validation completed"
      
      - name: 🔍 Check File Permissions
        run: |
          echo "🔍 Checking file permissions..."
          
          # Check if files are readable
          if [ -r "logistics-lynx/package.json" ]; then
            echo "✅ package.json is readable"
          else
            echo "❌ package.json is not readable"
            exit 1
          fi
          
          # Check workflow files
          for workflow in .github/workflows/*.yml; do
            if [ -r "$workflow" ]; then
              echo "✅ $workflow is readable"
            else
              echo "❌ $workflow is not readable"
              exit 1
            fi
          done
          
          echo "✅ File permissions check completed"
      
      - name: 📊 Local Validation Summary
        run: |
          echo "## 🏠 Local Validation Results"
          echo ""
          echo "**Status:** ✅ All local validations passed"
          echo "**Repository Structure:** ✅ Valid"
          echo "**YAML Syntax:** ✅ Valid"
          echo "**JSON Syntax:** ✅ Valid"
          echo "**File Permissions:** ✅ Valid"
          echo ""
          echo "### 🎯 What This Means:"
          echo "- Your code structure is correct"
          echo "- Configuration files are valid"
          echo "- No syntax errors found"
          echo "- Ready for local development"
          echo ""
          echo "### 🔧 Next Steps:"
          echo "1. **Continue local development** with npm run dev"
          echo "2. **Use GitHub Codespaces** for cloud development"
          echo "3. **Wait for network issues to resolve** for CI/CD"
          echo ""
          echo "### 💡 Development Options:"
          echo "- **Local:** npm install && npm run dev"
          echo "- **Cloud:** Use GitHub Codespaces"
          echo "- **Manual:** Build and deploy manually"
