
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# yaml-language-server: disableContextAccess: true

name: 🌐 Network Connectivity Diagnostic

on:
  push:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      debug_level:
        description: 'Debug output level'
        required: true
        default: 'basic'
        type: choice
        options: [minimal, basic, verbose]

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  network-diagnostic:
    name: 🌐 Network Connectivity Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      # Environment variables with localhost fallbacks
      ENVIRONMENT_NAME: ${{ vars.ENVIRONMENT_NAME || 'development' }}
      APP_URL: ${{ vars.APP_URL || 'http://localhost:8080' }}
    
    steps:
      - name: 🔍 Test Connectivity
        run: |
          echo "🌐 Testing network connectivity..."
          echo "Environment: $ENVIRONMENT_NAME"
          echo "App URL: $APP_URL"
          
          # Test basic connectivity
          curl -fsS --connect-timeout 10 https://httpbin.org/get || echo "❌ httpbin.org unreachable"
          curl -fsS --connect-timeout 10 https://api.github.com || echo "❌ GitHub API unreachable"
          
          echo "✅ Network diagnostic complete"

      - name: 📊 Diagnostic Summary
        run: |
          {
            echo "## 🌐 Network Diagnostic Results"
            echo "- Environment: \`$ENVIRONMENT_NAME\`"
            echo "- App URL: \`$APP_URL\`"
            echo "- Status: ✅ Complete"
          } >> "$GITHUB_STEP_SUMMARY"
