name: 🧪 Test Quick Fix Workflow

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths:
      - '.github/workflows/quick-fix.yml'

permissions:
  contents: read
  actions: read

jobs:
  test-quick-fix:
    name: 🧪 Test Quick Fix
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 🔍 Validate Quick Fix Workflow
        run: |
          echo "🔍 Validating quick-fix.yml workflow..."
          
          if [[ -f ".github/workflows/quick-fix.yml" ]]; then
            echo "✅ quick-fix.yml exists"
            
            # Check YAML syntax
            if python3 -c "import yaml; yaml.safe_load(open('.github/workflows/quick-fix.yml'))" 2>/dev/null; then
              echo "✅ YAML syntax is valid"
            else
              echo "❌ YAML syntax error"
              exit 1
            fi
            
            # Check for required fields
            if grep -q "^name:" .github/workflows/quick-fix.yml; then
              echo "✅ Has name field"
            else
              echo "❌ Missing name field"
              exit 1
            fi
            
            if grep -q "^on:" .github/workflows/quick-fix.yml; then
              echo "✅ Has trigger field"
            else
              echo "❌ Missing trigger field"
              exit 1
            fi
            
            if grep -q "^jobs:" .github/workflows/quick-fix.yml; then
              echo "✅ Has jobs field"
            else
              echo "❌ Missing jobs field"
              exit 1
            fi
            
          else
            echo "❌ quick-fix.yml not found"
            exit 1
          fi
          
          echo "✅ Quick fix workflow validation passed"

      - name: 📊 Test Summary
        if: always()
        run: |
          {
            echo "## 🧪 Quick Fix Test Results"
            echo ""
            echo "**Status:** \`${{ job.status }}\`"
            echo "**Repository:** \`${{ github.repository }}\`"
            echo "**Branch:** \`${{ github.ref_name }}\`"
            echo "**Commit:** \`${{ github.sha }}\`"
            echo ""
            echo "### ✅ What Was Tested"
            echo "- Quick fix workflow file existence"
            echo "- YAML syntax validation"
            echo "- Required field presence"
            echo ""
            echo "### 🔧 Next Steps"
            echo "1. Run the actual quick-fix workflow manually"
            echo "2. Test different validation levels"
            echo "3. Verify all functionality works as expected"
          } >> "$GITHUB_STEP_SUMMARY"
