name: Test Syntax

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Which environment to test?
        required: true
        type: choice
        default: staging
        options: [staging, production]

jobs:
  syntax:
    name: Validate config & contexts
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test Variables and Secrets
        env:
          ENVIRONMENT_NAME: ${{ inputs.environment }}
          STAGING_URL: ${{ vars.STAGING_URL || 'https://staging.example.com' }}
          PRODUCTION_URL: ${{ vars.PRODUCTION_URL || 'https://example.com' }}
          N8N_ENABLED: ${{ vars.N8N_ENABLED || 'false' }}
          N8N_BASE_URL: ${{ vars.N8N_BASE_URL || '' }}
          DEPLOYMENT_WEBHOOK_URL: ${{ secrets.DEPLOYMENT_WEBHOOK_URL || '' }}
          N8N_API_KEY: ${{ secrets.N8N_API_KEY || '' }}
        run: |
          echo "=== Environment Configuration Test ==="
          echo "ENVIRONMENT_NAME: $ENVIRONMENT_NAME"
          
          # Determine APP_URL based on environment
          if [ "$ENVIRONMENT_NAME" = "production" ]; then
            APP_URL="$PRODUCTION_URL"
          else
            APP_URL="$STAGING_URL"
          fi
          echo "APP_URL: $APP_URL"
          
          echo "N8N_ENABLED: $N8N_ENABLED"
          echo "N8N_BASE_URL set? $([ -n "$N8N_BASE_URL" ] && echo "yes" || echo "no")"
          echo "DEPLOYMENT_WEBHOOK_URL set? $([ -n "$DEPLOYMENT_WEBHOOK_URL" ] && echo "yes" || echo "no")"
          echo "N8N_API_KEY set? $([ -n "$N8N_API_KEY" ] && echo "yes" || echo "no")"
          
          echo "=== Test Complete ==="
